#!/bin/sh

uci set network.MOD_1='interface'
uci set network.MOD_1.proto='dhcp'
uci set network.MOD_1.device='wwan0_1'

uci set network.MOD_2='interface'
uci set network.MOD_2.proto='dhcp'
uci set network.MOD_2.device='wwan1_1'

uci set network.MOD_3='interface'
uci set network.MOD_3.proto='dhcp'
uci set network.MOD_3.device='wwan2_1'

uci set network.MOD_4='interface'
uci set network.MOD_4.proto='dhcp'
uci set network.MOD_4.device='wwan3_1'

uci add_list  firewall.@zone[1].network='MOD_1'
uci add_list  firewall.@zone[1].network='MOD_2'
uci add_list  firewall.@zone[1].network='MOD_3'
uci add_list  firewall.@zone[1].network='MOD_4'

uci commit network
uci commit firewall
/etc/init.d/firewall reload
/etc/init.d/network reload
